name: Api Docker Image CI

on:
  push:
    branches:
      - 'main'
    paths:
      - NotamManagement.Api/**
      - NotamManagement.Core/**

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build the Docker image
        run: |
          echo ${{ secrets.REGISTRY_PASSWORD }} | docker login registry.jazper.dk --username ${{ secrets.REGISTRY_USERNAME }} --password-stdin
          docker build -f ./Api.Dockerfile -t registry.jazper.dk/notam-management-api:latest .
          docker push registry.jazper.dk/notam-management-api:latest
